### ISSUE TITLE
install command seems incorrect

### ISSUE THREAD

**Issue by dereknex** [vmware/ansible-coreos-bootstrap#7]
I got `[WARNING]: - vmware.coreos-bootstrap was NOT installed successfully: - sorry, vmware.coreos-bootstrap was not found on https://galaxy.ansible.com.` error when try execute `ansible-galaxy install vmware.coreos-bootstrap`.  but `ansible-galaxy install vmware.ansible-coreos-bootstrap` is correct. 

cloud u please change it?

**Comment by sigma** [comment]
that's odd. it seems that galaxy did reset a bunch of names.
anyway, that should be fixed now. Thanks for reporting !
